import type { Metadata } from 'next';
import Link from 'next/link';
import { raleway, roboto_slab, montserrat } from '@/utils/fonts';
import './reset.css';
import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={raleway.className}>
        <header>
          <Link href="/" className="nav-link">
            Is this wise?
          </Link>
        </header>

        <nav>
          <Link v-if="isLoggedIn" href="/rate-advice" className="nav-link">
            Rate Advice
          </Link>
          <Link v-if="isLoggedIn" href="/history" className="nav-link">
            My History
          </Link>
          <div v-if="isLoggedIn" className="nav-link">
            Logout
          </div>
          <Link v-else href="/login" className="nav-link">
            Login
          </Link>
        </nav>
        <main className="content-box">{children}</main>
      </body>
    </html>
  );
}
